name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Build Lambda package
        run: |
          cd terraform/lambda
          zip -r ../lambda.zip .
          cd ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install npm dependencies
        run: npm install
      
      - name: Run Tests
        run: npm tests

      - name: Install Syft and Gripe
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh

      - name: Generate SBOM
        run: |
          syft . -o json > sbom.json

      - name: Scan with Grype
        run: |
          grype sbom:sbom.json -o json | tee grype-report.json
          if grep -q '"severity": "Critical"\|"severity": "High"' grype-report.json; then
              echo "High or Critical vulnerability found! Failing build."
              exit 1
          fi

      - name: Upload SBOM and Grype report
        uses: actions/upload-artifact@v3
        with:
          name: sbom-grype
          path: |
            sbom.json
            grype-report.json

      - name: Run Cypress Tests
        run: npm run cypress:run
